### PR TITLE
Check if the 4 GB memory allocation failed.

### LINKED ISSUE #953: Check if the 4 GB memory allocation failed
This might happen if the user for some reason has a really low pagefile size or disabled it entirely, we should warn the user about it if it happens.

### PR DESCRIPTION
**Pull request by blueskythlikesclouds**
Closes #953.

Requires proper English text and localization. Localization is needed because the installer can run perfectly fine until the game boots, and the user can select a different language at the start.

### CODE REVIEW

**Comment by hyperbx** [comment]
English text proposal:

---

Failed to allocate game memory.

Please make sure that:

- You meet the minimum system requirements (8 GB).
- Your pagefile is configured with at least 4-8 GB of virtual memory.

---

```
Failed to allocate game memory.\n\nPlease make sure that:\n\n- You meet the minimum system requirements (8 GB).\n- Your pagefile is configured with at least 4-8 GB of virtual memory.
```

File: UnleashedRecomp/locale/locale.cpp [hunk 1]
```diff
@@ -703,6 +703,17 @@ std::unordered_map<std::string_view, std::unordered_map<ELanguage, std::string>>
             { ELanguage::Italian,  "Impossibile trovare il modulo \"%s\".\n\nAssicurati che:\n\n- Hai estratto questa copia di Unleashed Recompiled correttamente e non solo il file *.exe.\n- Non stai eseguendo Unleashed Recompiled da un file *.zip." }
         }
     },
+    {
+        "System_MemoryAllocationFailed",
+        {
+            { ELanguage::English,  "Memory allocation failed blablabla enable your pagefile, ensure it's minimum 4 or 8 GB blablablabla" },
```
Comment (hyperbx) [inline UnleashedRecomp/locale/locale.cpp:709]: English text proposal:

---

Failed to allocate game memory.

Please make sure that:

- You meet the minimum system requirements (8 GB).
- Your pagefile is configured with at least 4-8 GB of virtual memory.

---

```suggestion
            { ELanguage::English,  "Failed to allocate game memory.\n\nPlease make sure that:\n\n- You meet the minimum system requirements (8 GB).\n- Your pagefile is configured with at least 4-8 GB of virtual memory." },
```

**Review by hyperbx — CHANGES_REQUESTED** [review]

**Comment by hyperbx** [comment]
@brianuuu @Kitzuku @LJSTARbird @DarioSamo @NextinMono The following string needs localisation:

```
{ ELanguage::English,  "Failed to allocate game memory.\n\nPlease make sure that:\n\n- You meet the minimum system requirements (8 GB).\n- Your pagefile is configured with at least 4-8 GB of virtual memory." }
```

**Comment by brianuuu** [comment]
`{ ELanguage::Japanese,  "ゲームメモリの割り当てに失敗しました\n\n次の点を確認してください：\n\n※最小システム要件（8 GB）を満たしていること。\n※ページファイルに少なくとも4～8 GBの仮想メモリが設定されていること" }`

**Comment by Kitzuku** [comment]
```
{ ELanguage::German, "Fehler beim Zuweisen des Spielspeichers.\n\nBitte stelle sicher, dass:\n\n- Die Mindestanforderungen für das System erfüllt sind (8 GB).\n- Die Auslagerungsdatei mit mindestens 4-8 GB virtuellem Speicher konfiguriert ist." }
```

**Comment by NextinMono** [comment]
```
{ ELanguage::Italian,  "Impossibile allocare la memoria per il gioco.\n\nAssicurati che:\n\n- Soddisfi i requisiti minimi di sistema (8 GB).\n- Il tuo pagefile sia configurato con almeno 4 o 8 GB di memoria virtuale." }
```

**Comment by LJSTARbird** [comment]
```
{ ELanguage::French,  "Échec d'allocation de la mémoire du jeu.\n\nVeuillez vous assurer que :\n\n- Vous disposez de la configuration minimale requise (8 Go).\n- Votre fichier d’échange est configuré avec au moins 4 à 8 Go de mémoire virtuelle." }
```

**Comment by blueskythlikesclouds** [comment]
@NextinMono Can you double check the official Windows translation for page file?

**Comment by NextinMono** [comment]
```
{ ELanguage::Italian,  "Impossibile allocare la memoria per il gioco.\n\nAssicurati che:\n\n- Soddisfi i requisiti minimi di sistema (8 GB).\n- Il tuo file di paging sia configurato con almeno 4 o 8 GB di memoria virtuale." }
```

**Review by DeaTh-G — APPROVED** [review]

**Review by hyperbx — APPROVED** [review]
