### PR TITLE
Fix "Disable Boost Filter" code not affecting certain parts of the game.

### LINKED ISSUE #1279: the disable boost audio filter code don't work in Eggmanland
the disable boost audio filter code don't work in Eggmanland
I've tried doing Eggmanland with only this code and its not working there

### PR DESCRIPTION
**Pull request by DeaTh-G**
Fixes #1279.

### CODE REVIEW

File: UnleashedRecomp/patches/misc_patches.cpp [hunk 1]
```diff
@@ -147,12 +147,18 @@ PPC_FUNC(sub_824C1E60)
...
+// we set the third argument to zero no matter what (if the code is on).
+PPC_FUNC_IMPL(__imp__sub_82B4DB48);
+PPC_FUNC(sub_82B4DB48)
 {
-    if (Config::DisableBoostFilter)
+    if (Config::DisableBoostFilter && strcmp((const char*)(base + ctx.r4.u32), "boost") == 0)
     {
-        if (r11.u32 == 1)
-            r11.u32 = 0;
+        ctx.f1.f64 = 0.0f;
```
Comment (blueskythlikesclouds) [inline UnleashedRecomp/patches/misc_patches.cpp:160]:
```suggestion
        ctx.f1.f64 = 0.0;
```

**Review by blueskythlikesclouds — CHANGES_REQUESTED** [review]

**Review by blueskythlikesclouds — APPROVED** [review]
